[package]
name = "deravel-filesystem-tar"
version = "0.0.0"
edition = "2024"

[dependencies]
deravel-kernel-api = { path = "../../kernel-api" }
deravel-interfaces = { path = "../../interfaces" }
log = "0.4"
